source 'https://rubygems.org'

gem 'rails', '4.0.4'
gem 'sass-rails'
gem 'coffee-rails'
gem 'activesupport', require: 'active_support'
gem 'uglifier'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'slim'
gem 'bson_ext'
gem 'mongoid', github: 'mongoid/mongoid'
gem 'bcrypt'

group :development, :test do
  gem 'spring'
  gem 'rspec-rails'
  gem 'capybara'
  gem 'poltergeist'
  gem 'fabrication'
  gem 'faker'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'letter_opener'
end